-- USE sql_challenge;

-- ===========================================
-- DAY 48 : REVENUE ANALYSIS
-- ===========================================

-- 1. Find Total Business Revenue

SELECT
    SUM(payment_amount) AS total_business_revenue
FROM cleaned_payments;


-- 2. Find Daily Revenue

SELECT
    payment_date,
    SUM(payment_amount) AS daily_revenue
FROM cleaned_payments
GROUP BY payment_date
ORDER BY payment_date;


-- 3. Find Monthly Revenue Trend

SELECT
    MONTH(payment_date) AS month_no,
    MONTHNAME(payment_date) AS month_name,
    SUM(payment_amount) AS monthly_revenue
FROM cleaned_payments
GROUP BY
    MONTH(payment_date),
    MONTHNAME(payment_date)
ORDER BY month_no;


-- 4. Find Revenue Generated by Each Product

SELECT
    p.product_id,
    p.product_name,
    SUM(od.quantity * p.price) AS total_revenue
FROM cleaned_products p

JOIN cleaned_order_details od
ON p.product_id = od.product_id

GROUP BY
    p.product_id,
    p.product_name

ORDER BY total_revenue DESC;


-- 5. Find Customer-wise Revenue

SELECT
    c.customer_id,
    c.customer_name,
    SUM(p.payment_amount) AS total_revenue
FROM cleaned_customers c

JOIN cleaned_orders o
ON c.customer_id = o.customer_id

JOIN cleaned_payments p
ON o.order_id = p.order_id

GROUP BY
    c.customer_id,
    c.customer_name

ORDER BY total_revenue DESC;


-- 6. Find Category-wise Revenue

SELECT
    pr.category,
    SUM(od.quantity * pr.price) AS total_revenue
FROM cleaned_products pr

JOIN cleaned_order_details od
ON pr.product_id = od.product_id

GROUP BY
    pr.category

ORDER BY total_revenue DESC;


-- 7. Find the Day Generating Highest Revenue

SELECT
    payment_date,
    SUM(payment_amount) AS total_revenue
FROM cleaned_payments

GROUP BY payment_date

ORDER BY total_revenue DESC

LIMIT 1;