-- USE sql_challenge;

-- ===========================================
-- DAY 46 : PRODUCT ANALYSIS
-- ===========================================

-- 1. Find products sold in the highest quantity

SELECT
    p.product_id,
    p.product_name,
    SUM(od.quantity) AS total_quantity_sold
FROM cleaned_products p
JOIN cleaned_order_details od
ON p.product_id = od.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_quantity_sold DESC;


-- 2. Find the least selling products

SELECT
    p.product_id,
    p.product_name,
    SUM(od.quantity) AS total_quantity_sold
FROM cleaned_products p
JOIN cleaned_order_details od
ON p.product_id = od.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_quantity_sold ASC;


-- 3. Find revenue generated by each product

SELECT
    p.product_id,
    p.product_name,
    SUM(od.quantity * p.price) AS total_revenue
FROM cleaned_products p
JOIN cleaned_order_details od
ON p.product_id = od.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_revenue DESC;


-- 4. Find total sales for each category

SELECT
    p.category,
    SUM(od.quantity * p.price) AS total_sales
FROM cleaned_products p
JOIN cleaned_order_details od
ON p.product_id = od.product_id
GROUP BY
    p.category
ORDER BY total_sales DESC;


-- 5. Find the highest priced product that was sold

SELECT
    p.product_id,
    p.product_name,
    p.category,
    p.price
FROM cleaned_products p
JOIN cleaned_order_details od
ON p.product_id = od.product_id
ORDER BY p.price DESC
LIMIT 1;


-- 6. Find average product price category-wise

SELECT
    category,
    AVG(price) AS avg_price
FROM cleaned_products
GROUP BY category
ORDER BY avg_price DESC;


-- 7. Find daily quantity sold for each product

SELECT
    o.order_date,
    p.product_id,
    p.product_name,
    SUM(od.quantity) AS total_quantity_sold
FROM cleaned_products p
JOIN cleaned_order_details od
ON p.product_id = od.product_id
JOIN cleaned_orders o
ON od.order_id = o.order_id
GROUP BY
    o.order_date,
    p.product_id,
    p.product_name
ORDER BY
    o.order_date,
    total_quantity_sold DESC;